# Generated by Django 4.2.17 on 2025-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(default='products/default.jpg', upload_to='products/large/', verbose_name='Изображение (большое)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(default='products/default.jpg', upload_to='products/medium/', verbose_name='Изображение (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(default='products/default.jpg', upload_to='products/small/', verbose_name='Изображение (маленькое)'),
            preserve_default=False,
        ),
    ]
