# Generated by Django 4.2.17 on 2025-05-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Идентификатор категории')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Идентификатор подкатегории')),
                ('image', models.ImageField(upload_to='subcategories/', verbose_name='Изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Податегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('name',),
            },
        ),
    ]
